[package]
name = "media-compressor"
version = "0.2.0"
description = "Size-targeted video and image compressor"
authors = ["sak0x7d5"]
edition = "2021"

[lib]
# The `_lib` suffix keeps the lib name distinct from the bin name on Windows.
# See https://github.com/rust-lang/cargo/issues/8519
name = "media_compressor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "time", "fs", "process", "io-util"] }
ffmpeg-sidecar = "2.5.2"
sha2 = "0.11.0"
tauri-plugin-dialog = "2.7.2"
base64 = "0.23.1"
tauri-plugin-single-instance = "2.4.3"
ureq = "3.4.0"
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"
trash = "5.2.6"

[dev-dependencies]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[target."cfg(windows)".dependencies]
clipboard-win = "5.4.1"
winreg = "0.56.0"
